### ISSUE TITLE
Failed installation via pip on Mac OS Sierra

### ISSUE THREAD

**Issue by sarahucl94** [wiheto/teneto#8] opened 2018-07-17 16:20 UTC
I keep getting this error when trying to install the package on Python3.6 and Python2.7:

`/usr/bin/clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -stdlib=libc++ -Iinclude -Iigraphcore/include -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/CPMVertexPartition.cpp -o build/temp.macosx-10.6-intel-3.6/src/CPMVertexPartition.o
    clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
    error: command '/usr/bin/clang' failed with exit status 1`

I think it's due to mistake in installation of louvain package. Any help is much appreciated.

**Comment by wiheto** [comment] 2018-08-03 08:00
Hi there, 

First - I am really sorry for the late reply. I was on holiday when this was posted and I missed the email notification. 

Second - The problem is iGraph (which is the louvain package depends on). I have heard from multiple people now that the dependency on igraph is frustrating and it will be removed in the next version. I have been sent multiple errors of different library problems on both Windows and Mac OS which I am unable to solve (sorry). 

## The solution

I will release a new  version within a week which removes the dependency on igraph (I will then close this issue). This will however remove communitydetection until I find a suitable solution.
(I made my own community detection I while ago, it is just slower than the igraph implementation and I need to think about what to do here). 

## Until I update teneto

You have two options (1) dig into igraph and Mac OS installation help ([starting point](http://igraph.org/python/doc/tutorial/install.html)) (2) the docker image in the repo works fine (it's what I use daily).

**Comment by wiheto** [comment] 2018-08-03 09:11
Teneto 0.3.5 released where all iGraph dependencies are removed (as too is teneto.communitydetection). So pip install teneto should work for you now. Let me know if this still doesn't work.

**Closed as completed by wiheto** 2018-08-03 09:11 UTC
Labels: bug
